### ISSUE TITLE
No Issues but Question

### ISSUE THREAD

**Issue by Davennix** [Rdimo/DiscordRAT#1]
Can you do when you close the exe file that continues to run in the background?

**Comment by Davennix** [comment]
And when you install it and start it the file attaches itself to other files so that when you uninstall it you still have

**Comment by Davennix** [comment]
And A Minecraft/Paypal Grabber sry for asking so much

**Comment by Rdimo** [comment]
xd no worries for asking so much

**Comment by Rdimo** [comment]
added the startup command so thats already done

**Comment by Davennix** [comment]
Okay thanks xD So I mean If The person opens the exe file and then closes that it does not close properly but should run in the background and spread, is such a thing possible?

**Comment by Rdimo** [comment]
yes that's possible

**Comment by Davennix** [comment]
Ah okay nice, Uhm I have a problem when I do /startup it only comes interaction failed

**Comment by Davennix** [comment]
And how do I get the keylogger data?

**Comment by Davennix** [comment]
And how do I get the keylogger data?

**Comment by Rdimo** [comment]
interaction failed is fixed now, it did work but it just didn't send a message back saying that it worked, thats what I fixed

**Comment by Davennix** [comment]
Ah Okay nice, But how do I get the data from the keylogger

**Comment by Davennix** [comment]
Yes but it only says "Successfully dumped all the logs" But there is nothing at temp folder or anywhere else / and /stopkeylogger does not work :/

**Comment by Rdimo** [comment]
it doesn't?

**Comment by Rdimo** [comment]
lemme fix that soon hold on

**Comment by Davennix** [comment]
jo have another important question, I do not know if you accept orders But I'm me times so free and make you times An offer :)

So my idea:
A Discord token grabber/data grabber/keylogger/pc control with live picture data So a multi tool (Most things you have already approx.) and would like to have an extra program where I have all accounts (victims) listed with their data and everything, And an interface where I can give people access to this program.

How much would that cost?
Would pay in Eth

**Comment by Rdimo** [comment]
already working on a program like that, join my discord if your intrested whe nI release beta

**Comment by Davennix** [comment]
Oh okay I'm in, how long do you think it will take for the beta release?

**Comment by Davennix** [comment]
Okay hope they get this done quickly :), do you know how I get the windows defender dings gone and how I make that program keep running in the background when the victim tries to close the program

**Comment by Rdimo** [comment]
ye I know that but I have that for my paid rat that coming out soon

**Comment by Davennix** [comment]
Hm interessting how much will it cost? do you know that already

**Comment by Rdimo** [comment]
idk dont have a set price but, thinking about $10-$20

**Comment by Davennix** [comment]
Alr
