### ISSUE TITLE
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

### ISSUE THREAD

**Issue by throwawayorsoe** [Rdimo/DiscordRAT#5]
### **When running the R.A.T tool you tent to get a few errors popping up in the Python IDE** 

`Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\client.py:416> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord_slash\client.py", line 440, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id=scope)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access`

**_Havent modified the code apart from adding the bot token and guild id to the guild list._**

**It runs fine but will not allow you to view or use the slash commands due to the errors above**

**Comment by Rdimo** [comment]
alright looks like the bot doesn't have enough permission to execute the command, did you give it admin perms?

**Comment by throwawayorsoe** [comment]
> alright looks like the bot doesn't have enough permission to execute the command, did you give it admin perms?

I have, its permissions are all correct.

**Comment by Rdimo** [comment]
oh alr nvm then, here contact me on [discord](https://Cheataway.com) and ill help you, alot easier for me to help there rather than here

**Comment by throwawayorsoe** [comment]
> oh alr nvm then, here contact me on [discord](https://Cheataway.com) and ill help you, alot easier for me to help there rather than here

I have sent an friend request on my alternate account

**Comment by throwawayorsoe** [comment]
### **FIXED**

To stop this from happening is just by doing the following:

`g = []`

*and your fixed....*

**Comment by Akane124** [comment]
I don't get it, do I just add g = [] in a new line? I also have the error
